// <auto-generated />
namespace XavSpace.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class IsArchivedfieldadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsArchivedfieldadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201502172112324_IsArchived-field-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
