// <auto-generated />
namespace XavSpace.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class noticeupdatedandtagsremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noticeupdatedandtagsremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201501142109363_notice-updated-and-tags-removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
